monolog:

    handlers:
        main:
            channels:
                - "!event"

        sentry.error:
            type: sentry
            dsn: '%env(SENTRY_DSN)%'
            level: error

        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
